org: qendresa
app: jewerly-store
service: jewerly-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"
  environment:
    JEWELRY_STORE_TABLE_NAME: serverless-present-x

functions:
  - ${file(./serverless/functions/jewelry.yml)}
resources:
  - ${file(./resources/dynamo-table.yml)}

useDotenv: true
